name: Security Scan with AI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures at least one previous commit is available

      - name: Generate Code Diff
        run: |
          git fetch --unshallow || true  # Ensure full commit history
          git diff HEAD^ > code_diff.txt || git diff --staged > code_diff.txt || echo "No diff available" > code_diff.txt
          echo "Code Diff:"
          cat code_diff.txt

      - name: Send Code Diff to AI Agent
        id: security_scan
        run: |
          DIFF_CONTENT=$(jq -Rs . < code_diff.txt)  # Properly escape the diff content
          JSON_PAYLOAD=$(jq -n --arg question "Does this code contain security vulnerabilities?" --arg diff "$DIFF_CONTENT" '{question: $question, diff: $diff}')
          
          echo "Sending payload: $JSON_PAYLOAD"  # Debugging

          RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            https://agentapi.vercel.app/chat)

          echo "$RESPONSE" > ai_response.json
          jq . ai_response.json  # Pretty-print JSON for debugging
          echo "status=$(jq -r '.status // "Error: No status found"' ai_response.json)" >> $GITHUB_ENV

      - name: Display AI Security Scan Report
        run: |
          echo "## 🔍 AI Security Scan Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "### 📌 Code Diff" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          cat code_diff.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "### 🤖 AI Analysis" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat ai_response.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Take Action Based on AI Decision
        run: |
          if [[ "$status" == "Approve PR: No vulnerabilities found" ]]; then
            echo "✅ No vulnerabilities detected. PR is safe."
          elif [[ "$status" == "Request changes: Minor issue detected" ]]; then
            echo "⚠️ Requesting changes due to minor security issues."
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"body": "⚠️ Security scan found minor issues. Please review and fix."}' \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
          elif [[ "$status" == "Block PR: Critical vulnerability found" ]]; then
            echo "🚨 Critical vulnerability detected! Blocking PR."
            exit 1
          else
            echo "❌ Unknown status from AI. Review manually."
          fi
