name: Security Scan on Push

on:
  push:
    branches:
      - main  # Runs only on pushes to main branch
      - dev   # (Optional) Add other branches if needed

permissions:
  contents: read  # Allow access to repo contents

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we get the latest commit for diff

      - name: Get Code Diff
        run: |
          git diff HEAD^ > code_diff.txt
          echo "✅ Code diff extracted"

      - name: Send Code Diff to AI Agent
        id: security_scan
        run: |
          RESPONSE=$(curl -X POST -H "Content-Type: application/json" \
            -d "{\"diff\": \"$(cat code_diff.txt)\"}" \
            https://agentapi.vercel.app/chat)

          echo "AI Response: $RESPONSE" >> $GITHUB_STEP_SUMMARY
          echo "status=$(echo $RESPONSE | jq -r '.status')" >> $GITHUB_ENV

      - name: Take Action Based on AI Decision
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          STATUS="${{ env.status }}"

          if [[ "$STATUS" == "Approve Commit: No vulnerabilities found" ]]; then
            echo "✅ Commit Approved."

          elif [[ "$STATUS" == "Warning: Minor issue detected" ]]; then
            echo "⚠️ Security Warning: Minor issues found."
            echo "Check the AI report in the workflow summary."

          elif [[ "$STATUS" == "Block Commit: Critical vulnerability found" ]]; then
            echo "🚨 Blocking commit due to critical vulnerabilities."
            exit 1
          fi
