name: Slack Notification

on: 
  push:
    branches:
      - main  # Change if needed

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-type: application/json" \
          --data '{
            "channel": "#your-channel", 
            "text": "🚀 A new push was made to *main*! Commit: ${{ github.event.head_commit.message }}"
          }' \
          https://slack.com/api/chat.postMessage
