name: AI Security Scan & Slack Notification

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we have the last commit for diff comparison

      - name: Generate Code Diff
        run: |
          git diff HEAD^ HEAD || echo "No previous commit" > code_diff.txt
          cat code_diff.txt  # Debugging

      - name: Send Code Diff to AI Agent
        id: ai_scan
        run: |
          DIFF_CONTENT=$(jq -Rs . < code_diff.txt)
          if [ -z "$DIFF_CONTENT" ] || [ "$DIFF_CONTENT" == "\"\"" ]; then
            echo "⚠️ No code diff available. Skipping AI analysis."
            echo '{"response": "No code diff available"}' > ai_response.json
          else
            JSON_PAYLOAD=$(jq -n --arg question "Analyze this code for security vulnerabilities" --arg diff "$DIFF_CONTENT" '{question: $question, diff: $diff}')
            echo "🔍 Sending AI request to API..."
            RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" https://agentapi.vercel.app/chat)
            echo "$RESPONSE" > ai_response.json
            if [ ! -s ai_response.json ]; then
              echo "❌ No AI response available!"
              echo '{"response": "No AI response available"}' > ai_response.json
            fi
          fi
          echo "✅ AI Response Received:"
          cat ai_response.json  # Debugging

      - name: Upload AI Response
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ai_response
          path: ai_response.json
          retention-days: 1

  send_slack_message:
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      - name: Download AI Response
        uses: actions/download-artifact@v4
        with:
          name: ai_response

      - name: Send Slack Message
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          if [ -z "$SLACK_BOT_TOKEN" ]; then
            echo "❌ Slack token is missing!"
            exit 1
          fi

          AI_RESPONSE=$(jq -r '.response' ai_response.json)
          TRUNCATED_RESPONSE=$(echo "$AI_RESPONSE" | head -c 2000 | jq -Rs .)

          SLACK_MESSAGE="🔍 *AI Security Scan Report*\n\n*Analysis:*\n$TRUNCATED_RESPONSE\n"

          echo "📤 Sending message to Slack..."
          RESPONSE=$(curl -s -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-type: application/json" \
            --data "{\"channel\": \"C08EEK2A8EN\", \"text\": $SLACK_MESSAGE}" \
            https://slack.com/api/chat.postMessage)

          echo "📝 Slack Response: $RESPONSE"
          if [[ $(echo "$RESPONSE" | jq -r '.ok') != "true" ]]; then
            echo "❌ Failed to send Slack message!"
            exit 1
          fi
